#pragma once


//MAP

#define NUM_ANTS 100
#define MAP_WIDTH 256
#define MAP_HEIGHT 256
#define MAP_CELLS MAP_WIDTH*MAP_HEIGHT


//=====================ANT=============================

#define SENSOR_RADIUS_TINY 1
#define SENSOR_RADIUS_SMALL 2
#define SENSOR_RADIUS_MEDIUM 4
#define SENSOR_DISTANCE 8
#define SENSOR_RADIUS_LARGE 8
#define SENSOR_RADIUS_HUGE 16

#define JOB_SENSOR_RADIUS 15
#define JOB_INTERACT_RADIUS 10




//BODY

#define COLLISION_GROUP_SIZE 8
#define COLLISION_GRID_WIDTH  (MAP_WIDTH/COLLISION_GROUP_SIZE)+1
#define COLLISION_GRID_HEIGHT (MAP_HEIGHT/COLLISION_GROUP_SIZE)+1

//TASKS

#define TASK_SUCCESS_THRESHOLD 5
//#define TASK_

//====================JOBS====================

#define JOB_MAX_AMOUNT	100
#define PACKET_SIZE		1


//=======================PHEROMONES===================

#define MAX_NUMBER_OF_TASKS				16
#define DEFAULT_PHEROMONES_NUMBER		4
#define NUMBER_OF_PHEROMONE_PAIRS		MAX_NUMBER_OF_TASKS+DEFAULT_PHEROMONES_NUMBER
#define EXPLORED_PHEROMONE_ID			MAX_NUMBER_OF_TASKS+0
#define PATH_PHEROMONE_ID				MAX_NUMBER_OF_TASKS+1
#define SUCCESS_PHEROMONE_ID			MAX_NUMBER_OF_TASKS+2
#define FAILURE_PHEROMONE_ID			MAX_NUMBER_OF_TASKS+3
//#define OUTER_CONTAINS_MAP_RESOLUTION	32

#define PHEROMONE_FLOOR					0.2
#define PHEROMONE_DECAY					0.997
#define PHEROMONE_DECAY_FAST			PHEROMONE_DECAY * PHEROMONE_DECAY * PHEROMONE_DECAY